geo_key <- structure(list(Era = c("Cenozoic", "Cenozoic", "Cenozoic", "Cenozoic",
                                  "Cenozoic", "Cenozoic", "Cenozoic", "Cenozoic", "Cenozoic", "Cenozoic",
                                  "Cenozoic", "Cenozoic", "Cenozoic", "Cenozoic", "Cenozoic", "Cenozoic",
                                  "Cenozoic", "Cenozoic", "Cenozoic", "Cenozoic", "Cenozoic"),
                          Period = c("Paleogene", "Paleogene", "Paleogene", "Paleogene",
                                     "Paleogene", "Paleogene", "Paleogene", "Paleogene", "Paleogene",
                                     "Neogene", "Neogene", "Neogene", "Neogene", "Neogene", "Neogene",
                                     "Neogene", "Neogene", "Quaternary", "Quaternary", "Quaternary",
                                     "Quaternary"), Epoch = c("Paleocene", "Paleocene", "Paleocene",
                                                              "Eocene", "Eocene", "Eocene", "Eocene", "Oligocene", "Oligocene",
                                                              "Miocene", "Miocene", "Miocene", "Miocene", "Miocene", "Miocene",
                                                              "Pliocene", "Pliocene", "Pleistocene", "Pleistocene", "Pleistocene",
                                                              "Holocene"), Stage = c("Danian", "Selandian", "Thanetian",
                                                                                     "Ypresian", "Lutetian", "Bartonian", "Priabonian", "Rupelian",
                                                                                     "Chattian", "Aquitanian", "Burdigalian", "Langhian", "Serravallian",
                                                                                     "Tortonian", "Messinian", "Zanclean", "Piacenzian", "Gelasian",
                                                                                     "Calabrian", "Chibanian", "Holocene"), Interval = c("Early Paleocene",
                                                                                                                                         "Middle Paleocene", "Late Paleocene", "Early Eocene", "Middle Eocene",
                                                                                                                                         "Middle Eocene", "Late Eocene", "Early Oligocene", "Late Oligocene",
                                                                                                                                         "Early Miocene", "Early Miocene", "Middle Miocene", "Middle Miocene",
                                                                                                                                         "Late Miocene", "Late Miocene", "Early Pliocene", "Late Pliocene",
                                                                                                                                         "Early Pleistocene", "Middle Pleistocene", "Late Pleistocene",
                                                                                                                                         "Holocene"), Max = c(6.6e+07, 61600000, 59200000, 5.6e+07,
                                                                                                                                                              47800000, 41200000, 37800000, 33900000, 28100000, 2.3e+07,
                                                                                                                                                              20400000, 15970000, 13820000, 11630000, 7250000, 5330000,
                                                                                                                                                              3600000, 2580000, 1810000, 780000, 10000), Min = c(61600000,
                                                                                                                                                                                                                 59200000, 5.6e+07, 47800000, 41200000, 37800000, 33900000,
                                                                                                                                                                                                                 28100000, 2.3e+07, 20400000, 15970000, 13820000, 11630000,
                                                                                                                                                                                                                 7250000, 5330000, 3600000, 2580000, 1810000, 780000, 10000,
                                                                                                                                                                                                                 0)), class = "data.frame", row.names = c(NA, -21L))

df <- structure(list(Taxa = c("Cuon alpinus", "Cuon alpinus", "Cuon alpinus",
                              "Cuon alpinus", "Cuon alpinus", "Cuon alpinus", "Cuon alpinus",
                              "Cuon alpinus", "Cuon alpinus", "Cuon alpinus", "Cuon alpinus",
                              "Cuon alpinus", "Cuon alpinus", "Cuon alpinus", "Cuon alpinus",
                              "Cuon alpinus", "Cuon alpinus", "Cuon alpinus", "Cuon alpinus",
                              "Cuon alpinus", "Cuon alpinus", "Cuon alpinus", "Cuon alpinus",
                              "Cuon alpinus", "Cuon alpinus", "Cuon alpinus", "Cuon alpinus",
                              "Cuon alpinus", "Cuon alpinus"), Country = c("Austria", "Italy",
                                                                           "Italy", "Italy", "Italy", "France", "Belgium", "Austria", "Austria",
                                                                           "Belgium", "Italy", "Italy", "Italy", "Italy", "Italy", "China",
                                                                           "China", "China", "China", "Java", "Java", "India", "Java", "Georgia",
                                                                           "Georgia", "Spain", "Spain", "Spain", "Germany"), Latitude = c(48.1188,
                                                                                                                                          41.655, 41.534, 40.13, 40.13, 42.71, 50.489, 47.50638, 47.2247222222222,
                                                                                                                                          50.591, 42.636, 42.636, 43.952, 44.165, 44.165, 24.2228, 39.6833,
                                                                                                                                          33.133306, 23.51, -7.787, -7.787, 23.083, -7.606, 42.008, 42.008,
                                                                                                                                          43.298, 40.112, 38.763, 51.755), Longitude = c(16.9398, 12.991,
                                                                                                                                                                                         13.487, 18.2763, 18.2763, 2.77, 5.027, 15.36638, 15.3380555555555,
                                                                                                                                                                                         5.441, 12.645, 12.645, 10.331, 10.152, 10.152, 109.0872, 122.0167,
                                                                                                                                                                                         110.217861, 111.795, 110.527, 110.527, 79.25, 110.681, 43.0105,
                                                                                                                                                                                         43.0105, -3.7, -0.05, -0.191, 10.843), Age = c("Middle_Pleistocene",
                                                                                                                                                                                                                                        "Lare Pleistocene", "600000", "27000", "holocene", "Early_Pleistocene",
                                                                                                                                                                                                                                        "middle plesitocne", "400000", "30000", "middle_pleistocene",
                                                                                                                                                                                                                                        "late_pleistocene", "15000", "650000", "middle_pleistocene",
                                                                                                                                                                                                                                        "late_pleistocene", "late_pleistocene", "late_pleistocene", "late_pleistocene",
                                                                                                                                                                                                                                        "middle_pleistocene", "middle_pleistocene", "holocene", "6000",
                                                                                                                                                                                                                                        "middle_pleistocene", "middle_pleistocene", "5000", "Holocene?",
                                                                                                                                                                                                                                        "late_pleistocene", "20000", "late_pleistocene")), class = c("tbl_df",
                                                                                                                                                                                                                                                                                                     "tbl", "data.frame"), row.names = c(NA, -29L))
